tablelandnetwork/studio

packages/web/components/hash-display.tsx, packages/web/components/metric-card.tsx, packages/web/components/tableland-table.tsx, packages/web/lib/utils.ts
fixes: https://linear.app/tableland/issue/ENG-823/the-table-pages-table-name-card-has-issues-with-overflow-and-word
The metric card on the table page has issues with the layout and you cannot click to copy the table name.
This PR updates the layout to handle text overflow with an ellipsis truncation, and it enable the same click to copy functionality as the wallet public key in the header.
=> (web) update to layout of metric card, and enable click to copy

packages/web/app/[team]/(team)/page.tsx, packages/web/components/ui/alert.tsx
Exploring some ways of simplifying the team page content rendering logic...
fixes: https://linear.app/tableland/issue/ENG-817/when-i-look-at-someone-elses-personal-team-page-it-says-its-my-team
There are a few variables that affect display logic below
- authenticated
- authorized
- is the team a personal team
- sub-case when authenticated, is the viewer the team's person?
- existence of projects
These combine to make quite a few cases, seems like it's about 14. With so
many different potential displays, i wanted to explore ways to simplify where we can.
I've added some screenshots since it's kind of time consuming to setup all the accounts and teams locally
=> (web) refactor team page render logic

package-lock.json, package.json, packages/api/src/index.ts, packages/api/src/trpc.ts, packages/cli/test/setup.ts, packages/web/app/[team]/(team)/people/page.tsx, packages/web/app/api/trpc/[trpc]/route.ts, packages/web/app/invite/page.tsx, packages/web/app/layout.tsx, packages/web/app/new-team/page.tsx, packages/web/app/page.tsx, packages/web/lib/session.ts, packages/web/package.json, packages/web/trpc/server.ts
While reviewing #231 I noticed that the consumers of the api package have to have iron-session as a dependency.  It seems like that should be a dep of api and the api package can contain the session logic.
Let's discuss in office hours
=> extracting iron-session into api only

packages/api/src/routers/deployments.ts, packages/store/src/api/deployments.ts, packages/web/app/[team]/[project]/(project)/deployments/[[...slug]]/_components/sidebar.tsx, packages/web/app/[team]/[project]/(project)/deployments/[[...slug]]/page.tsx, packages/web/components/projects-referencing-table.tsx, packages/web/components/tableland-table.tsx
On the tableland table page, created a new card that lists all Studio projects that reference the table. This required a new `store` function which is also exposed throught the `api` package.
Closes ENG-743
=> Display list of projects using table

package-lock.json, packages/nonce/package.json, packages/nonce/src/main.ts, packages/web/package.json, packages/web/vercel.json
Included here:
- updates the nonce manager to ensure that the `delta:*` keys have an automatic expiration.
- increase vercel max function duration to 60 seconds.
The combination of these two things should illiminate the issue of nonce deltas getting stuck when vercel timeout errors occur.
=> (nonce) set expire on delta redis key

package-lock.json, packages/nonce/package.json, packages/nonce/src/main.ts, packages/nonce/test/main.test.ts, packages/nonce/test/process-with.js, packages/web/.env.example, packages/web/lib/wallet.ts, packages/web/package.json
Enable using the in-memory nonce manager for local dev.
If the `KV_LOCAL_DEV` environment variable is set then the in-memory nonce manager is used, otherwise you must provide redis connection env vars as usual.
=> (web,nonce) enabling local dev without redis

packages/web/app/[team]/(team)/page.tsx, packages/web/app/[team]/(team)/people/page.tsx, packages/web/app/[team]/[project]/(project)/page.tsx, packages/web/app/[team]/[project]/(project)/tables/[[...slug]]/page.tsx, packages/web/app/[team]/[project]/[def]/page.tsx, packages/web/lib/api-helpers.ts
When we query for team or project based on a slug in the url, often the slug is wrong because of a user typo or web crawler or hacker. This was resulting in error stack traces printed in our logs for the NOT_FOUND error and a generic error component being displayed to the user. 
This PR provides some helpers to those API calls that catches the error, checks if it's a 404, and displays our 404 not found page if so.
=> API helpers to catch not found error

packages/web/app/[team]/(team)/people/_components/info.tsx, packages/web/app/[team]/[project]/[def]/page.tsx, packages/web/app/_components/footer.tsx
Found a few more places where color classes where defined as specific values instead of based on description.  This change removes light-mode colors and should allow us to toggle between dark and light if we choose to do so in the future.
=> (web) replace color number with descriptor

package-lock.json, packages/api/package.json, packages/web/components/sign-in-button.tsx, packages/web/package.json
The Brave browser includes the siwe message scheme regardless of if it is provided.  The default is `https`, so when we are working locally we need to explicitly provide the `http` scheme.
fixes: https://linear.app/tableland/issue/ENG-849/local-dev-team-invites-dont-seem-to-work-in-brave
=> (web) fix siwe Brave browser incompat in local

packages/web/app/[team]/(team)/layout.tsx, packages/web/app/[team]/[project]/_components/sidebar.tsx, packages/web/app/[team]/[project]/layout.tsx
I noticed the sidebar was shrinking and obscuring some of the nav items in some cases. This makes it so the sidebar can't shrink.
=> Sidebar layout fix

packages/web/app/[team]/[project]/[env]/[table]/page.tsx, packages/web/app/table/[name]/page.tsx, packages/web/components/table.tsx
There are two cases where this is relevant:
1. Viewing a tableland table at the `/table/<table id>` url
2. Viewing a table in the context of a project
In both cases, the table being loaded might be for a chain we no longer support.
In the first case, it's as simple as just displaying the error message that says "unsupported chain id". 
In the second case, we still need to display enough UI to convey the error message and also give the user a way to delete the now-invalid deployment by un-deploying the table. The solution looks something like this:
(Note, I forced the UI into an error state, so some of the surrounding data will not be what you expect in a real scenario)
=> Handle unsupported chain deployments

packages/api/src/routers/deployments.ts, packages/api/src/routers/tables.ts, packages/store/src/api/auth.ts, packages/store/src/api/teams.ts, packages/store/src/custom-types/index.ts, packages/store/src/helpers.ts, packages/web/app/table/[name]/page.tsx, packages/web/components/columns.tsx, packages/web/components/def-columns.tsx, packages/web/components/new-def-form.tsx
There is a Tableland quirk where, if you create an `Integer` column with a `primary key` constraint, it ends up also with an `autoincrement` modifier once it is materialized on Tableland. We can't specify the `autoincrement` part of `integer primary key autoincrement` in our `create` statement or else we get a syntax error... But when we ask the validator for information about a table, while importing a table, for example, `integer primary key autoincrement` is the constraint information that comes back.
This PR correctly deals with this situation for `Schema` data that is created by Studio and hasn't been deployed to Tableland as well as `Scheama`s that are imported from existing Tableland tables. It provides informative UI so the user understands what is going on.
Create table …
=> Handle and display auto incrementing pks properly

package-lock.json, packages/cli/package.json, packages/cli/src/cli.ts, packages/store/src/custom-types/index.ts, packages/validators/src/common.ts, packages/validators/src/validators/defs.ts
fixes https://linear.app/tableland/issue/ENG-854/handle-aliases-field-in-rc-file
=> fix studio cli fails when rc file comes from general cli

packages/web/app/[team]/(team)/layout.tsx, packages/web/app/[team]/(team)/page.tsx, packages/web/app/[team]/[project]/[env]/[table]/page.tsx, packages/web/app/[team]/[project]/layout.tsx
In the case of viewing a project's table that has been deployed and the displayed data table is wider than the screen, the whole page was getting a horizonal scroll bar. The desired behaviour is the page content is never wider than the screen, and the data table component itseld scrolls horizontally. This change does that.
=> Fix layout

package-lock.json, packages/api/src/root.ts, packages/api/src/routers/users.ts, packages/store/src/api/users.ts, packages/web/app/[team]/[project]/[env]/[table]/page.tsx, packages/web/app/_components/latest-tables.tsx, packages/web/app/page.tsx, packages/web/app/table/[name]/page.tsx, packages/web/components/acl.tsx, packages/web/components/console.tsx, packages/web/components/data-table.tsx, packages/web/components/def-details.tsx, packages/web/components/edit-cell.tsx, packages/web/components/exec-deployment.tsx, packages/web/components/hash-display.tsx, packages/web/components/table-cell.tsx, packages/web/components/table-data-types.ts, packages/web/components/table-data.tsx, packages/web/components/table-details.tsx, packages/web/components/table.tsx, packages/web/lib/utils.ts, packages/web/lib/validator-queries.ts, packages/web/lib/wagmi-ethers.ts, packages/web/package.json, packages/web/tsconfig.json, packages/web/types.d.ts
Title says it all. This also leverages and displays new data related to table owner and ACL.
=> Editable table data

packages/web/app/_components/primary-header-item.tsx, packages/web/components/env-switcher.tsx, packages/web/components/project-switcher.tsx, packages/web/components/team-switcher.tsx
For shared components, I'm realizing it's better to allow customization of the tailwind styles always on the outer most html element, and rely on te css cascase to influence child compoenent styles.
I use that approach here and then customize the switchers in the breadcrumb nav to look a bit better.
=> Better styling for switcher components

package-lock.json, packages/api/package.json, packages/cli/package.json, packages/store/package.json, packages/validators/package.json, packages/web/package.json
This updates the sdk and sql parser so that definitions imported from tables that don't have prefixes work in the console.
Most specifically the Dimo project needs to work with the console.
I tested this in the vercel preview below.
=> update sdk and sql parser to fix console

packages/nonce/src/main.ts
A user reported an issue creating an account this week.  This resulted from the nonce delta key not having an expire.  
After some debugging and reading, I believe that the redis incrby command is clearing the expire value and the key is never being removed if the chain provider requests timeout or are throttled.
Here is the relevant error log when the provider request fails:
```
Error resetting delta: Error: could not coalesce error (error={ "code": -32007, "message": "15/second request limit reached - reduce calls per second or upgrade your account at quicknode.com" }, payload={ "id": 79, "jsonrpc": "2.0", "method": "eth_getTransactionReceipt", "params": [ "0x133cd82245df7ea68820efff1e0c34e3d5d8a1165f2cf927c51ae96736de571e" ] }, code=UNKNOWN_ERROR, version=6.12.1)
at a …
```
=> (nonce) ensure incrby does not remove ttl

package-lock.json, packages/validators/src/validators/defs.ts, packages/web/app/_components/new-env-form.tsx, packages/web/app/_components/new-team-form.tsx, packages/web/components/edit-def.tsx, packages/web/components/form.tsx, packages/web/components/import-table-form.tsx, packages/web/components/new-def-form.tsx, packages/web/components/new-project-form.tsx, packages/web/components/registration-dialog.tsx, packages/web/package.json
When creating a definition, validate there are no duplicate column names.
Closes ENG-850
=> Don't allow duplicate column names

packages/api/src/routers/projects.ts, packages/cli/src/commands/project.ts, packages/cli/test/sql/setup_studio_test_tables.sql, packages/client/src/index.ts, packages/store/src/api/projects.ts, packages/store/src/schema/index.ts, packages/validators/src/validators/projects.ts, packages/web/app/[org]/[project]/[env]/console/page.tsx, packages/web/app/[org]/[project]/_components/sidebar.tsx, packages/web/app/[org]/[project]/settings/_components/edit-project.tsx, packages/web/components/console-tabs.tsx, packages/web/components/console.tsx, packages/web/components/new-project-form.tsx, packages/web/components/sidebar-link.tsx, packages/web/drizzle/0003_noisy_slyde.sql, packages/web/drizzle/meta/0003_snapshot.json, packages/web/drizzle/meta/_journal.json
Dimo requested the ability to use both the alias table names and the global table names in the console.  This adds a toggle the allows the user to choose which option they would like to write queries in.
=> (web) allow using global table names in console

packages/api/src/session-data.ts, packages/api/src/trpc.ts
I realized that already logged in sessions (from before #305 was merged) will have their org data saved under the old key `personalTeam`. This change accounts for that and moves that information to the new key. We can delete this code after some time.
=> Migrate old personalTeam to personalOrg in session data

packages/web/app/[org]/(org)/_components/new-project-button.tsx, packages/web/app/[org]/(org)/settings/_components/edit-org.tsx, packages/web/app/[org]/[project]/[env]/[table]/_components/deploy-button.tsx, packages/web/app/[org]/[project]/settings/_components/env.tsx, packages/web/app/[org]/[project]/settings/_components/envs.tsx, packages/web/app/_components/primary-header-item.tsx, packages/web/components/profile.tsx, packages/web/components/table-menu.tsx
This fixes a whole class of bugs where, after making a data mutation on the server side, you don't see data update on the client. It turns out that if you refresh the router, it needs to happen after any navigation, or else the router refresh gets cancelled.
This also uses a feature of tRPC I previously didn't know about that makes refreshing data on the client side cleaner.
=> Router refresh fix + tRPC improvement
